# Generated by Django 5.2.1 on 2025-05-22 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('published_date', models.DateField()),
                ('isbn_number', models.CharField(max_length=13, unique=True)),
                ('genre', models.CharField(max_length=50)),
                ('summary', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Books',
                'ordering': ['title'],
            },
        ),
    ]
